HangOutClubWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('Login.urls')),
    path('profile/', include('user_profile.urls')),
    path('roulette/', include('roulette.urls')),
    path('', include('Home.urls')),
]

Home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.get_home_page, name='home'),
    path('perform_task/', views.perform_task, name='perform_task'),
    path('delete_task/', views.delete_task, name='delete_task'),
    path('get_rating/', views.get_rating, name='get_rating'),
    path('completed_tasks/', views.completed_tasks, name='completed_tasks'),
    path('get_user_punishment/', views.get_user_punishment, name='get_user_punishment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'login'
urlpatterns = [
    path('sign-in/', views.sign_in, name='sign-in'),
    path('sign-up/', views.sign_up, name='sign-up'),
    path('sign-out/', views.sign_out, name='sign-out'),
    path('sign-up/qr_code/<str:first_name>/<str:last_name>/<str:username>/<str:password>', views.sign_up_qr_code,
         name='sign_up_qr_code'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

roulette/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'roulette'
urlpatterns = [
    path('', views.get_roulette_page, name='roulette'),
    path('to_do_quest/', views.to_do_quest, name='to_do_quest'),
    path('perform_quest/', views.perform_quest, name='perform_quest'),
    path('fail_quest/', views.fail_quest, name='fail_quest'),
    path('check_exist_completing_quest/', views.check_exist_completing_quest, name='check_exist_completing_quest'),
    path('get_quest_data/', views.get_quest_data, name='get_quest_data'),
    path('get_history_list/', views.get_history_list, name='get_history_list'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'user_profile'
urlpatterns = [
    path('edit/password', views.edit_password, name='edit_password'),
    path('edit/name', views.edit_name, name='edit_name'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Sum, Count


class Gifts(models.Model):
    name = models.CharField(max_length=80, db_index=True, verbose_name='Название')
    description = models.CharField(max_length=200, db_index=True, verbose_name='Описание')
    blocked_until = models.DateTimeField(verbose_name='Заблокировано до')
    complete_until = models.DateTimeField(verbose_name='Завершиться', null=True)
    image = models.ImageField(upload_to='gift_image/%Y/%m/%d', blank=True, verbose_name='Картинка')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Призы'
        verbose_name_plural = 'Призы'

    def __str__(self):
        return self.name

    def unblocked(self):
        if timezone.now() >= self.blocked_until:
            return True
        else:
            return False

    def unblocked_via(self):
        return int((self.blocked_until - timezone.now()).total_seconds())

    def dont_complete(self):
        return timezone.now() >= self.complete_until


class Category(models.Model):
    name = models.CharField(max_length=30, db_index=True, verbose_name='Название')
    color = models.CharField(max_length=30, db_index=True, verbose_name='Цвет(HEX)', default='#ffffff')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Quests(models.Model):
    category = models.ForeignKey(Category, related_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=60, db_index=True, verbose_name='Заголовок')
    description = models.TextField(blank=True, verbose_name='Описание')
    reward = models.SmallIntegerField(verbose_name='Награда')
    DIFFICULTIES = (
        (0, 'Low'),
        (1, 'Normal'),
        (2, 'High'),
    )
    complexity = models.SmallIntegerField(verbose_name='Сложность', default=0, choices=DIFFICULTIES)
    amount_available_user = models.SmallIntegerField(verbose_name='Количество доступное для пользователя', default=1)
    available = models.BooleanField(default=True, verbose_name='Активность')

    objects = models.Manager()
    completed_count = models.Manager()

    class Meta:
        ordering = ('reward',)
        verbose_name = 'Задание'
        verbose_name_plural = 'Задания'

    def __str__(self):
        return self.title

    def completed_count(self, user, quest):
        return UserQuests.objects.filter(user=user, quest_completed=quest).aggregate(completed_count=Count('id'))['completed_count']


class UserQuests(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    completed_at = models.DateTimeField(auto_now_add=True, verbose_name='Выполнено')
    quest_completed = models.ForeignKey(Quests, on_delete=models.CASCADE, verbose_name='Выполненное задание',
                                        blank=True)

    class Meta:
        verbose_name = 'Выполненные задания'
        verbose_name_plural = 'Выполненное задание'

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}; {self.quest_completed};' \
               f' {self.completed_at}'


class UserProfileManager(models.Manager):
    def add_points(self, user, points: str):
        if '-' in points:
            points = points.replace('-', '')
            return self.remove_points(user, points)
        user_profile = self.get(user=user)
        user_profile.points += int(points)
        user_profile.save()

    def remove_points(self, user, points: str):
        if '-' in points:
            points = points.replace('-', '')
            return self.add_points(user, points)
        user_profile = self.get(user=user)
        user_profile.points -= int(points)
        user_profile.save()

    def get_points(self, user):
        user_profile = self.get(user=user)
        return user_profile.points

    def get_ranking(self):
        return self.all().order_by('-points')


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    points = models.SmallIntegerField(default=0)
    objects = UserProfileManager()

    class Meta:
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'

    def __str__(self):
        return self.user.username

Home/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Gifts, Quests, Category, UserQuests, UserProfile
from django.utils import timezone
from urllib.parse import parse_qs
from django.contrib.auth.models import User
from django.db.models import Max, Count, OuterRef, Case, When, IntegerField
from django.db.models import Q
import json


def get_home_page(request):
    if request.user.is_authenticated:
        gifts = Gifts.objects.all()
        quests = Quests.objects.filter(available=True)
        categories = Category.objects.all()
        show_gift = None
        gift = None
        user_quests = UserQuests.objects.filter(user=request.user)
        for quest in quests:
            quest.user_completion = user_quests.filter(quest_completed=quest, user=request.user).count()

        if gifts:
            gift = gifts[0]
        return render(request, 'Home/index.html', {'user': request.user, 'gift': gift,
                                                   'quests': quests, 'categories': categories,
                                                   'user_quests': user_quests})
    else:
        return redirect(reverse('login:sign-up'))


def task_manipulator(request, delete_task=False):

    data = parse_qs(str(request.body.decode('utf-8')))
    user = User.objects.get(pk=data['user_id'][0])
    quest = Quests.objects.get(pk=data['quest_id'][0])
    points = data['points'][0]

    if delete_task:
        try:
            UserQuests.objects.filter(user=user, quest_completed=quest)[0].delete()
            UserProfile.objects.remove_points(user, points)
            return JsonResponse({'status': 'success'})
        except IndexError:
            return JsonResponse({'error': 'Data invalid'})

    else:
        count_available_from_user = quest.amount_available_user
        completed_user_count = UserQuests.objects.filter(quest_completed=quest, user=user).count()

        if count_available_from_user > completed_user_count:
            UserQuests(user=user, quest_completed=quest).save()
            UserProfile.objects.add_points(user, points)
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'error': 'Invalid request method'})


def perform_task(request):
    if request.method == 'POST':
        response = task_manipulator(request)
        return response
    else:
        return JsonResponse({'error': 'Invalid request method'})


def delete_task(request):
    if request.method == 'POST':

        task_manipulator(request, delete_task=True)
        return JsonResponse({'status': 'success'})
    else:
        return JsonResponse({'error': 'Invalid request method'})


def get_rating(request):
    if request.method == 'POST':
        users_rating = UserProfile.objects.get_ranking()
        return JsonResponse({'response': list(users_rating.values('user__id', 'user__first_name', 'user__last_name', 'points'))})


def completed_tasks(request):
    if request.method == 'POST':
        pass
    else:
        if request.user.is_authenticated:
            user_quests = UserQuests.objects.filter(user=request.user)
            added_quests = []
            # user_quests = UserQuests.objects.filter(user=request.user, quest_completed=True).annotate(
            #     user_completion=Count('user'))

            # for user_quest in user_quests:
            #     print(user_quest.user_completion)
            for user_quest in user_quests:

                if user_quest.quest_completed.id not in added_quests:
                    print(user_quest.quest_completed.id)
                    user_quest.user_completion = user_quests.filter(quest_completed=user_quest.quest_completed,
                                                                           user=request.user).count()
                    added_quests.append(user_quest.quest_completed.id)
            return render(request, 'Home/completed_tasks.html', {'user_quests': user_quests})


def get_user_punishment(request):
    if request.method == 'POST':
        data = parse_qs(str(request.body.decode('utf-8')))
        user_id = data['user_id'][0]
        user_quests = UserQuests.objects.filter(user__id=user_id)
        punishment_quests = Quests.objects.filter(available=True, category__name='Наказания').annotate(
            user_completion_count=Count(
                Case(
                    When(userquests__user__id=user_id, then=1),
                    output_field=IntegerField()
                )
            )
        )

        response_data = list(punishment_quests.values('id', 'category', 'category__color', 'complexity', 'title',
                                                      'description', 'reward', 'amount_available_user',
                                                      'user_completion_count'))
        return JsonResponse({'response': response_data})
        #return JsonResponse({'response': response_data})
        #return JsonResponse({'response': 'test'})

Home/templates/Home/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>{% block title %}{% endblock %}</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="{% static 'Home/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'Home/css/bootstrap-original.css' %}">
  {% block load_style %}
  {% endblock %}
  


</head>

<body>
  <header>
    {% block header %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a id="navbar_brand" class="navbar-brand" href="{% url 'home:home' %}">♂{{ user.first_name }} {{ user.last_name }}♂</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'home:home' %}">Главная
                <span class="visually-hidden">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'roulette:roulette' %}">Рулетка
                <span class="visually-hidden">(current)</span>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Профиль</a>
              <div class="dropdown-menu">
                
                <a class="dropdown-item" href="{% url 'user_profile:edit_name' %}">Изменить имя</a>
                <a class="dropdown-item" href="{% url 'user_profile:edit_password' %}">Изменить пароль</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'login:sign-out' %}">Выйти из клуба</a>
              </div>
            </li>
          </ul>
          <div class="d-flex">
            <input id="search-challenge" class="form-control me-sm-2" type="text" placeholder="Поиск задания">
            <button class="btn btn-secondary my-2 my-sm-0" type="button" onclick="search_challenge()">Поиск</button>
          </div>
        </div>
      </div>
    </nav>
    {% endblock %}
  </header>
  <main>
    <div id="background_image" class="container-fluid" style="z-index: -100; opacity: 40%; ;width: 100%; height: 100%; position: fixed; left: -4px; top: 0px; background-image: url({% static 'Home/img/gachi_simbol.png' %}); background-size: 60px;"></div>
    {% block content %}
    
    {% endblock %}
  </main>
  <footer>
    {% block footer %}
    {% endblock %}
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
    
  </script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  {% block js %}
  {% endblock %}
</body>

</html>

Home/templates/Home/completed_tasks.html
{% extends "Home/base.html" %}
{% load static %}
{% block title %}
    Gachi - Выполненные задания
{% endblock %}


{% block content %}
<div class="main-block" style="background-image: url({% static 'Home/img/gachi_simbol.png' %});"></div>

  {% if user_quests %}
    {% for quest in user_quests %}
      {% if quest.user_completion %}
        <article id="card-{{ forloop.counter }}" class="challenge col d-flex justify-content-center identifier-{{ quest.category.name }}">
          <div class="card text-white mb-3" style="width: 20rem; background-color: {{ quest.quest_completed.category.color }};">
            <div class="card-header d-flex">
              <div class="reward">{{ quest.quest_completed.reward }} BUCKS</div>
              <div class="container-fluid d-flex justify-content-end container-complexity">
                <div class="container-fluid d-flex justify-content-end container-complexity">
                  <span class="badge rounded-pill complexity hide">{{ quest.quest_completed.complexity }}</span>
                </div>
                <span id="card-count-{{ forloop.counter }}" class="badge bg-light mr-5">
                  {{ quest.user_completion }}/{{ quest.quest_completed.amount_available_user }}
                </span>
              </div>
            </div>
            <div class="card-body ">
              <h4 class="card-title challenge-title">{{ quest.quest_completed.title }}</h4>
              <p class="card-text challenge-description">{{ quest.quest_completed.description }}</p>
            </div>
            <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
              <button id="card-button-{{ forloop.counter }}" type="button" onclick="perform_task('{{ quest.user.id }}', '{{ quest.quest_completed.id }}', this, {{ quest.reward }})" class="btn btn-light">Выполнить</button>
            </div>  
          </div>
        </article>
      {% endif %}
    {% endfor %}
  {% else %}
  {% endif %}

{% endblock %}