HangOutClubWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('Login.urls')),
    path('profile/', include('user_profile.urls')),
    path('roulette/', include('roulette.urls')),
    path('', include('Home.urls')),
]

Home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.get_home_page, name='home'),
    path('perform_task/', views.perform_task, name='perform_task'),
    path('delete_task/', views.delete_task, name='delete_task'),
    path('get_rating/', views.get_rating, name='get_rating'),
    path('completed_tasks/', views.completed_tasks, name='completed_tasks'),
    path('get_user_punishment/', views.get_user_punishment, name='get_user_punishment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'login'
urlpatterns = [
    path('sign-in/', views.sign_in, name='sign-in'),
    path('sign-up/', views.sign_up, name='sign-up'),
    path('sign-out/', views.sign_out, name='sign-out'),
    path('sign-up/qr_code/<str:first_name>/<str:last_name>/<str:username>/<str:password>', views.sign_up_qr_code,
         name='sign_up_qr_code'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login/models.py
from django.db import models

# Create your models here.

Login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from Home.models import UserProfile
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.urls import reverse
from django.http import HttpResponse


def sign_out(request):
    logout(request)
    return redirect(reverse('login:sign-up'))


def sign_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            #return redirect(reverse('home:home'))
            return redirect(reverse('home:home'))
        else:
            return render(request, 'Login/sign-in/index.html', {'incorrect_input': 'true'})
    else:
        if request.user.is_authenticated:
            logout(request)
            return render(request, 'Login/sign-in/index.html')
        else:
            return render(request, 'Login/sign-in/index.html')


def sign_up(request):
    if request.user.is_authenticated:
        return redirect(reverse('home:home'))

    if request.method == 'POST':
        user_name = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        password = request.POST['password']
        try:
            user = User.objects.create_user(user_name, password=password, first_name=first_name, last_name=last_name)
        except IntegrityError:
            return render(request, 'Login/sign-up/index.html', {'incorrect_input': 'true'})
        login(request, user)
        UserProfile(user=user).save()
        return redirect(reverse('home:home'))
    return render(request, 'Login/sign-up/index.html')


def sign_up_qr_code(request, first_name, last_name, username, password):
    if request.user.is_authenticated:
        return redirect(reverse('home:home'))
    try:
        user = User.objects.create_user(username, password=password, first_name=first_name, last_name=last_name)
    except IntegrityError:
        return render(request, 'Login/sign-up/index.html')
    login(request, user)
    UserProfile(user=user).save()
    return redirect(reverse('home:home'))

Login/templates/Login/sign-in/index.html
{% extends "Login/base.html" %}
{% load static %}

{% block title %}
    Login
{% endblock %}
{% block content %}
<section class="ftco-section">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-6 col-lg-4">
				<div class="login-wrap p-0">
	      	<form action="{% url 'login:sign-in' %}" class="signin-form" method="post">
	      		<div class="form-group">
					{% if incorrect_input %}
	      				<input name="username" type="text" class="form-control is-invalid" id="inputInvalid" placeholder="Логин" required>
						<div class="invalid-feedback">Неправильный логин или пароль</div>
					{% else %}
						<input name="username" type="text" class="form-control" placeholder="Логин" required>
					{% endif %}
	      		</div>
            <div class="form-group">
              <input name="password" id="password-field" type="password" class="form-control" placeholder="Пароль" required>
              <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
            </div>
            <div class="form-group">
            	<button type="submit" class="form-control btn btn-primary submit px-3">Войти</button>
            </div>
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<p>Нету аккаунта?<a href="{% url 'login:sign-up' %}"> Зарегистрироваться</a></p>
				</div>
			</div>
			{% csrf_token %}
          </form>
	      </div>
			</div>
		</div>
	</div>
</section>
{% endblock %}